version: '3.8'

services:
  rusty-webserver:
    image: ghcr.io/olive-techno/ghcr_hello-time/rusty-webserver:main
    ports:
      - "3030:8080"
    environment:
      - GREETING_TEXT="Hello_world!!"
    restart: unless-stopped

