name: CI/CD

on:
  push:
    branches:
      - main # Or your main branch name
      - '*' # This will trigger on all branches
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Update Rust toolchain
        run: rustup update

      - name: Build the application
        run: cargo build --release

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | sed -e 's/[^a-zA-Z0-9]/-/g')
          IMAGE_NAME=ghcr.io/${{ github.repository }}/rusty-webserver:${BRANCH_NAME}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          
